version: '3.8'

services:
  nodebb:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '4567:4567' # comment this out if you don't want to expose NodeBB to the host, or change the first number to any port you want
    volumes:
      - nodebb-build:/usr/src/app/build
      - nodebb-uploads:/usr/src/app/public/uploads
      - nodebb-config:/opt/config
      - ./install/docker/setup.json:/usr/src/app/setup.json
    networks:
      - dev-net

volumes:
  nodebb-build:
    external:
      name: nodebb-build

  nodebb-uploads:
    external:
      name: nodebb-uploads

  nodebb-config:
    external:
      name: nodebb-config

networks:
  dev-net:
    name: vivune-dev-network
    external: true